"""Generate dist/SKSE/Plugins/OSEDReborn.ini from the defaults in src/Settings.h.

The binding table in src/Settings.cpp decides which keys exist and their order; the
inline initializers in src/Settings.h supply the values. Run after changing either.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
header = (root / "src/Settings.h").read_text(encoding="utf-8")
source = (root / "src/Settings.cpp").read_text(encoding="utf-8")

# namespace -> {name: (value, comment)}
defaults = {}
ns = None
for line in header.splitlines():
    m = re.match(r"\s*namespace (\w+)\s*$", line)
    if m:
        ns = m.group(1)
        continue
    m = re.match(r"\s*inline (bool|int|float|std::string) (\w+) = ([^;]+);\s*(?://\s*(.*))?", line)
    if m and ns:
        value = m.group(3).strip()
        if m.group(1) == "float":
            value = value.rstrip("f")
        elif m.group(1) == "std::string":
            value = value.strip('"')
        elif m.group(1) == "int" and "::" not in value and not re.fullmatch(r"-?\d+", value):
            value = {"kDirector": "2", "kAuto": "0"}.get(value, value)
        defaults.setdefault(ns, {})[m.group(2)] = (value, m.group(4) or "")

enum_values = {"kDirector": "2", "kAuto": "0"}
sections = {}
for sec, key, ns_name, var in re.findall(r'\{ "(\w+)", "(\w+)", &(\w+)::(\w+) \}', source):
    value, comment = defaults[ns_name][var]
    value = enum_values.get(value, value)
    sections.setdefault(sec, []).append((key, value, comment))

notes = {
    "General": "Master switches. Everything here is also on the SKSE Menu Framework pages (default key F1).",
    "Face": "Face engine. iMode: 0 Assist, 1 Enhanced, 2 Director (OSED owns the face). fStyle: 0 realistic, 1 cinematic, 2 anime.",
    "Body": "Toe curl / hand grip at climax. iCurlAxis: 0 X, 1 Y, 2 Z (bone-local).",
    "Skin": "Face overlays (\"Face [Ovl#]\"). Texture paths are relative to Data\\textures; an empty blush path auto-uses Female Makeup Suite's cheek blush if installed.",
    "LipSync": "Mouth follows the moan OStim plays (decoded from your voice-set .wav files at startup).",
    "Arousal": "Softbody Arousal. iSource: 0 auto (OSL first), 1 OSL Aroused, 2 SLO Aroused NG, 3 OStim excitement only.\n; Body blush uses \"Body [Ovl#]\" slots iOverlayFirstSlot .. +iOverlaySlots-1; set skee64.ini [Overlays/Body] iNumOverlays to at least 12.",
}

out = ["; OSED Reborn - edit in game via SKSE Menu Framework (OSED Reborn section).",
       "; Generated by scripts/gen_default_ini.py from src/Settings.h; the game rewrites this file when you press Save.", ""]
for sec, rows in sections.items():
    if sec in notes:
        out.append("; " + notes[sec])
    out.append(f"[{sec}]")
    for key, value, comment in rows:
        out.append(f"{key} = {value}")
    out.append("")
dest = root / "dist/SKSE/Plugins/OSEDReborn.ini"
dest.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {dest} ({sum(len(r) for r in sections.values())} keys)")
