# SPDX-License-Identifier: GPL-3.0-or-later
# OStim Standalone Immersive Sex (OSIS) - Copyright (C) 2026 jturnley
# Free software under the GNU General Public License v3 or later; see LICENSE.

"""Generate the default OSIS.ini of both editions from the defaults in src/Settings.h:
dist/SKSE/Plugins/OSIS.ini (full) and dist-lite/SKSE/Plugins/OSIS.ini (Lite).

The binding table in src/Settings.cpp decides which keys exist and their order; the
inline initializers in src/Settings.h supply the values. Rows inside `#if !OSIS_LITE`
blocks are left out of the Lite edition. Run after changing either file.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
header = (root / "src/Settings.h").read_text(encoding="utf-8")
source = (root / "src/Settings.cpp").read_text(encoding="utf-8")

# namespace -> {name: (value, comment)}
defaults = {}
ns = None
for line in header.splitlines():
    m = re.match(r"\s*namespace (\w+)\s*$", line)
    if m:
        ns = m.group(1)
        continue
    m = re.match(r"\s*inline (bool|int|float|std::string) (\w+) = ([^;]+);\s*(?://\s*(.*))?", line)
    if m and ns:
        value = m.group(3).strip()
        if m.group(1) == "float":
            value = value.rstrip("f")
        elif m.group(1) == "std::string":
            value = value.strip('"')
        elif m.group(1) == "int" and "::" not in value and not re.fullmatch(r"-?\d+", value):
            value = {"kDirector": "2", "kAuto": "0"}.get(value, value)
        defaults.setdefault(ns, {})[m.group(2)] = (value, m.group(4) or "")

enum_values = {"kDirector": "2", "kAuto": "0"}
binding = re.compile(r'\{ "(\w+)", "(\w+)", &(\w+)::(\w+) \}')


def sections_for(lite):
    sections = {}
    skip = False
    for line in source.splitlines():
        stripped = line.strip()
        if stripped == "#if !OSIS_LITE":
            skip = lite
            continue
        if stripped == "#endif":
            skip = False
            continue
        m = binding.search(line)
        if skip or not m:
            continue
        sec, key, ns_name, var = m.groups()
        value, comment = defaults[ns_name][var]
        value = enum_values.get(value, value)
        sections.setdefault(sec, []).append((key, value, comment))
    return sections


notes = {
    "General": "Master switches. Everything here is also on the SKSE Menu Framework pages (default key F1).\n; bAnimationHooks is read at startup: leave it on unless another mod's hook on the same calls conflicts.",
    "Face": "Face engine. iMode: 0 Assist, 1 Enhanced, 2 Director (OSED owns the face). fStyle: 0 realistic, 1 cinematic, 2 anime.",
    "Body": "Toe curl / hand grip at climax. iCurlAxis: 0 X, 1 Y, 2 Z (bone-local).",
    "Skin": "Face overlays (\"Face [Ovl#]\"). Texture paths are relative to Data\\textures; an empty blush path auto-uses Female Makeup Suite's cheek blush if installed. Tears only appear in non-consensual scenes, on the victim.",
    "LipSync": "Mouth follows the moan OStim plays (decoded from your voice-set .wav files at startup).\n; bYieldToDDF: stand down while Dynamic Dialogue Framework is installed (both drive the mouth).",
    "Voice": "The victim of a non-consensual scene: OStim moans muted, a cry for help that guards/allies answer, personality lines, a scream at the breaking climax, then hard breathing. Vanilla Skyrim.esm lines only.\n; iVictimVoice: 0 silent, 1 breathing only, 2 full. iResponders: 0 nobody, 1 guards, 2 guards and allies.",
    "Arousal": "Softbody Arousal. iSource: 0 auto (OSL first), 1 OSL Aroused, 2 SLO Aroused NG, 3 OStim excitement only.\n; Body blush uses \"Body [Ovl#]\" slots iOverlayFirstSlot .. +iOverlaySlots-1; set skee64.ini [Overlays/Body] iNumOverlays to at least 12.",
}
lite_notes = dict(notes)
lite_notes["Skin"] = "Face overlays (\"Face [Ovl#]\"). Texture paths are relative to Data\\textures; an empty blush path auto-uses Female Makeup Suite's cheek blush if installed."

for lite, folder in ((False, "dist"), (True, "dist-lite")):
    sections = sections_for(lite)
    edition_notes = lite_notes if lite else notes
    out = ["; OStim Standalone Immersive Sex - edit in game via SKSE Menu Framework (OSIS section).",
           "; Generated by scripts/gen_default_ini.py from src/Settings.h; the game rewrites this file when you press Save.", ""]
    for sec, rows in sections.items():
        if sec in edition_notes:
            out.append("; " + edition_notes[sec])
        out.append(f"[{sec}]")
        for key, value, comment in rows:
            out.append(f"{key} = {value}")
        out.append("")
    dest = root / folder / "SKSE/Plugins/OSIS.ini"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {dest} ({sum(len(r) for r in sections.values())} keys)")
