"""Assemble the combined MO2 mod `mods/OSED Reborn` from both halves of the project.

Active (mod root):   the SKSE plugin route - OSEDReborn.dll/.pdb from the xmake build, plus
                     everything under dist/ (laid out like Data/).
Inert fallback:      the four fixed Papyrus mods, merged under `optional/Papyrus Fallback/`.
                     The game never loads anything from Data/optional/, so the two engines
                     can't both drive faces; README.md says how to swap.

The output folder is generated: it is wiped and rebuilt on every run (only if it carries our
BUILD.txt marker). This script never builds anything itself; it warns when the DLL or a .pex
is older than its sources.

Usage: python tools/assemble_mod.py
"""
import datetime
import glob
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'mods', 'OSED Reborn')
FALLBACK = os.path.join(OUT, 'optional', 'Papyrus Fallback')
MARKER = 'Generated by tools/assemble_mod.py'
DLL_NAME = 'OSEDReborn'
BUILD_MODES = ['releasedbg', 'release', 'debug']  # preference order
PAPYRUS_MODS = ['OSED Core', 'OSED Body', 'OSED Living Skin', 'OSED Lip-Sync']

warnings = []


def newest(paths):
    return max((os.path.getmtime(p) for p in paths), default=0.0)


def files_under(d):
    for base, _dirs, names in os.walk(d):
        for n in names:
            yield os.path.join(base, n)


def place(src, dest, origin):
    """Copy src to dest; an existing identical file is fine, a different one is an error."""
    if os.path.exists(dest):
        if open(src, 'rb').read() != open(dest, 'rb').read():
            raise SystemExit('conflict: %s differs from the copy already placed at %s (from %s)'
                             % (src, os.path.relpath(dest, OUT), origin.get(dest)))
        return
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    shutil.copy2(src, dest)
    origin[dest] = os.path.relpath(src, ROOT)


def reset_output():
    if os.path.exists(OUT):
        build = os.path.join(OUT, 'BUILD.txt')
        if not (os.path.exists(build) and open(build, encoding='utf-8').readline().startswith(MARKER)):
            raise SystemExit('%s exists but was not made by this script; not deleting it.' % OUT)
        shutil.rmtree(OUT)
    os.makedirs(OUT)


def find_dll():
    for mode in BUILD_MODES:
        dll = os.path.join(ROOT, 'build', 'windows', 'x64', mode, DLL_NAME + '.dll')
        if os.path.exists(dll):
            if mode != BUILD_MODES[0]:
                warnings.append('using the %s DLL build, not %s' % (mode, BUILD_MODES[0]))
            return dll
    raise SystemExit('no %s.dll under build/windows/x64/{%s}; build it with xmake first'
                     % (DLL_NAME, ','.join(BUILD_MODES)))


def add_dll_route(origin):
    dll = find_dll()
    sources = [p for d in ('src', 'include') for p in files_under(os.path.join(ROOT, d))]
    if newest(sources) > os.path.getmtime(dll):
        warnings.append('%s is older than the newest file in src/ or include/: rebuild with xmake'
                        % os.path.relpath(dll, ROOT))
    plugins = os.path.join(OUT, 'SKSE', 'Plugins')
    place(dll, os.path.join(plugins, DLL_NAME + '.dll'), origin)
    pdb = os.path.splitext(dll)[0] + '.pdb'
    if os.path.exists(pdb):  # lets crash loggers name functions
        place(pdb, os.path.join(plugins, DLL_NAME + '.pdb'), origin)
    dist = os.path.join(ROOT, 'dist')
    for p in files_under(dist):
        place(p, os.path.join(OUT, os.path.relpath(p, dist)), origin)
    return dll


def add_papyrus_fallback(origin):
    for mod in PAPYRUS_MODS:
        base = os.path.join(ROOT, 'mods', mod)
        for psc in glob.glob(os.path.join(base, 'Scripts', 'Source', '*.psc')):
            pex = os.path.join(base, 'Scripts', os.path.splitext(os.path.basename(psc))[0] + '.pex')
            if not os.path.exists(pex) or os.path.getmtime(pex) < os.path.getmtime(psc):
                warnings.append('%s is missing or older than its source: run tools/compile_papyrus.py'
                                % os.path.relpath(pex, ROOT))
        for p in files_under(base):
            rel = os.path.relpath(p, base)
            if rel.lower() == 'readme.md':
                rel = 'README - %s.md' % mod
            place(p, os.path.join(FALLBACK, rel), origin)


def git_head():
    try:
        head = subprocess.run(['git', '-C', ROOT, 'rev-parse', '--short', 'HEAD'],
                              capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(['git', '-C', ROOT, 'status', '--porcelain', '--', 'mods', 'tools'],
                               capture_output=True, text=True).stdout
        dirty = [l for l in dirty.splitlines() if 'mods/OSED Reborn' not in l]
        return head + (' (+ uncommitted changes in mods/ or tools/)' if dirty else '')
    except (OSError, subprocess.CalledProcessError):
        return 'unknown'


README = """# OSED Reborn

OStim Expression Director (OSED) and its Body, Living Skin and Lip-Sync add-ons, rebuilt.
This folder is generated by `tools/assemble_mod.py`; `BUILD.txt` records what went into it.

## What is active

The SKSE plugin, `SKSE/Plugins/OSEDReborn.dll`. It has no plugin (.esp), no Papyrus scripts
and no MCM. Settings are in the SKSE Menu Framework (section "OSED Reborn") and in
`SKSE/Plugins/OSEDReborn.ini`.

`optional/Papyrus Fallback/` holds the fixed Papyrus versions of the four original mods. The
game never loads anything from an `optional` folder, so it is inert where it is.

## Before enabling

Disable the original **Ostim Expression Director (OSED)**, **OSED Body**, **OSED Living Skin**,
**OSED Enhanced Moan LipSync** and **Softbody Arousal** in MO2. This mod replaces all of them,
and two copies would fight over the same faces and bones. Start a new save for testing.

## Requirements

- DLL route: SKSE64, Address Library for SKSE Plugins, OStim Standalone, SKSE Menu Framework,
  RaceMenu (skin overlays), and Spell Perk Item Distributor (reads `OSED_Personality_DISTR.ini`).
- Papyrus fallback: OStim Standalone, SkyUI, PapyrusUtil SE, Mfg Fix NG, RaceMenu, SPID.

## Switching to the Papyrus fallback

1. Move `SKSE/Plugins/OSEDReborn.dll` and `.pdb` out of this folder (for example into `optional/`).
2. Move everything inside `optional/Papyrus Fallback/` up to this folder's root. Overwriting the
   facial expression files and the SPID ini is fine: they are identical.
3. Enable the four `.esp` files in MO2's plugin list, and start a new save.

The fallback's own READMEs are `README - <mod>.md`. Lip-Sync's fallback also needs the bake in
`BakeToolkit/` (the DLL's lip-sync does not).
"""


def main():
    reset_output()
    origin = {}
    dll = add_dll_route(origin)
    add_papyrus_fallback(origin)
    with open(os.path.join(OUT, 'README.md'), 'w', encoding='utf-8') as f:
        f.write(README)

    lines = [MARKER + ' on %s' % datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
             'Project commit: %s' % git_head(),
             'DLL: %s (built %s)' % (os.path.relpath(dll, ROOT),
                                     datetime.datetime.fromtimestamp(os.path.getmtime(dll)).strftime('%Y-%m-%d %H:%M')),
             '']
    lines += ['WARNING: ' + w for w in warnings]
    lines += ['', 'Files (size, source):']
    for dest in sorted(origin, key=lambda d: os.path.relpath(d, OUT).lower()):
        lines.append('  %-72s %9d  %s' % (os.path.relpath(dest, OUT), os.path.getsize(dest), origin[dest]))
    with open(os.path.join(OUT, 'BUILD.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print('Wrote %s: %d files' % (os.path.relpath(OUT, ROOT), len(origin) + 2))
    for w in warnings:
        print('WARNING: ' + w)
    return 0


if __name__ == '__main__':
    sys.exit(main())
