# SPDX-License-Identifier: GPL-3.0-or-later
# OStim Standalone Immersive Sex (OSIS) - Copyright (C) 2026 jturnley
# Free software under the GNU General Public License v3 or later; see LICENSE.

"""Assemble the MO2 mods of both editions from the xmake builds (`xmake build` makes both DLLs):
  mods/OStim Standalone Immersive Sex               the default release, compiled without the
                            non-consent features: build/lite/windows/x64/<mode>, plus dist-lite/ over dist/
  mods/OStim Standalone Immersive Sex (LoversLab)  the full plugin: build/windows/x64/<mode>, plus dist/
Each is OSIS.dll/.pdb plus the data folders (laid out like Data/). A file in an edition's
overlay folder replaces the one of the same path in dist/.

The output folder is generated: each run deletes the files the previous run listed in
BUILD-OSIS.txt and writes a fresh set. Anything else in the folder (an archive you packed from it,
for example) is left alone. Archives are never copied in. This script never builds anything
itself; it warns when the DLL is older than its sources.

Finally it writes mods/<mod>.zip for each, installable in MO2 (the mod's files at the zip root,
so MO2 names the mod after the zip and finds its data directly).

Usage: python tools/assemble_mod.py
"""
import datetime
import os
import re
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# (mod folder, build folder, data folders: overlays first, dist last, README title suffix,
#  source files the edition's DLL is built without)
EDITIONS = [
    ('OStim Standalone Immersive Sex', os.path.join('build', 'lite', 'windows', 'x64'), ['dist-lite', 'dist'], '',
     {'voice.cpp', 'voice.h', 'scenelock.cpp', 'scenelock.h', 'spellcast.cpp', 'spellcast.h'}),
    ('OStim Standalone Immersive Sex (LoversLab)', os.path.join('build', 'windows', 'x64'), ['dist'], ' (LoversLab edition)', set()),
]
OUT = os.path.join(ROOT, 'mods', EDITIONS[0][0])  # the edition being assembled
MARKER = 'Generated by tools/assemble_mod.py'
DLL_NAME = 'OSIS'
BUILD_MODES = ['releasedbg', 'release', 'debug']  # preference order
ARCHIVES = ('.7z', '.zip', '.rar')  # packed copies of a mod folder, not mod content
MANIFEST_LINE = re.compile(r'^  (.+?) +\d+  .+$')

warnings = []
skipped = []


def newest(paths):
    return max((os.path.getmtime(p) for p in paths), default=0.0)


def files_under(d, content_only=False):
    for base, _dirs, names in os.walk(d):
        for n in names:
            p = os.path.join(base, n)
            if content_only and n.lower().endswith(ARCHIVES):
                skipped.append(os.path.relpath(p, ROOT))
                continue
            yield p


def place(src, dest, origin):
    """Copy src to dest; an existing identical file is fine, a different one is an error."""
    if os.path.exists(dest):
        with open(src, 'rb') as a, open(dest, 'rb') as b:
            same = a.read() == b.read()
        if not same:
            raise SystemExit('conflict: %s differs from the copy already placed at %s (from %s)'
                             % (src, os.path.relpath(dest, OUT), origin.get(dest)))
        return
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    shutil.copy2(src, dest)
    origin[dest] = os.path.relpath(src, ROOT)


def reset_output():
    """Delete what the previous run made (the files BUILD-OSIS.txt lists, plus BUILD-OSIS.txt and README-OSIS.md),
    then prune empty folders. Other files stay. The folder itself stays too: Windows can't remove
    a folder that is open in Explorer or is some process's working directory."""
    os.makedirs(OUT, exist_ok=True)
    build = os.path.join(OUT, 'BUILD-OSIS.txt')
    if not os.path.exists(build):
        if os.listdir(OUT):
            raise SystemExit('%s has files but no BUILD-OSIS.txt from this script; not touching it.' % OUT)
        return
    with open(build, encoding='utf-8') as f:
        lines = f.read().splitlines()
    if not lines or not lines[0].startswith(MARKER):
        raise SystemExit('%s/BUILD-OSIS.txt was not written by this script; not touching the folder.' % OUT)
    ours = ['BUILD-OSIS.txt', 'README-OSIS.md']
    in_files = False
    for line in lines:
        if line.startswith('Files (size, source):'):
            in_files = True
        elif in_files and MANIFEST_LINE.match(line):
            ours.append(MANIFEST_LINE.match(line).group(1))
    for rel in ours:
        p = os.path.join(OUT, rel)
        if os.path.isfile(p):
            os.remove(p)
    for base, dirs, files in os.walk(OUT, topdown=False):
        if base != OUT and not os.listdir(base):
            os.rmdir(base)


def foreign_files(origin):
    """Files in the output folder that this run did not write."""
    made = {os.path.normcase(p) for p in origin} | {os.path.normcase(os.path.join(OUT, n)) for n in ('BUILD-OSIS.txt', 'README-OSIS.md')}
    return sorted(os.path.relpath(p, OUT) for p in files_under(OUT) if os.path.normcase(p) not in made)


def find_dll(build_dir):
    for mode in BUILD_MODES:
        dll = os.path.join(ROOT, build_dir, mode, DLL_NAME + '.dll')
        if os.path.exists(dll):
            if mode != BUILD_MODES[0]:
                warnings.append('using the %s DLL build, not %s' % (mode, BUILD_MODES[0]))
            return dll
    raise SystemExit('no %s.dll under %s/{%s}; build it with xmake first'
                     % (DLL_NAME, build_dir.replace(os.sep, '/'), ','.join(BUILD_MODES)))


def project_version():
    """The version xmake.lua declares, as "1.2.3"."""
    with open(os.path.join(ROOT, 'xmake.lua'), encoding='utf-8') as f:
        m = re.search(r'set_version\("([0-9]+\.[0-9]+\.[0-9]+)"\)', f.read())
    return m.group(1) if m else None


def check_dll_version(dll):
    """The version resource is UTF-16 in the PE, so the declared version shows up as plain
    bytes. Missing means xmake reused a stale generated plugin-info file: the DLL would load,
    report the previous version, and make every later log and crash report misleading."""
    want = project_version()
    if not want:
        warnings.append('could not read set_version from xmake.lua; DLL version not checked')
        return
    with open(dll, 'rb') as f:
        blob = f.read()
    if ('%s.0' % want).encode('utf-16-le') in blob:
        return
    raise SystemExit(
        '%s does not carry version %s: xmake kept a stale plugin-info file.\n'
        '  Delete build/.gens/*/windows/x64/*/commonlibsse-ng-plugin.cpp and build again.'
        % (os.path.relpath(dll, ROOT), want))


def add_dll_route(origin, build_dir, data_dirs, without):
    dll = find_dll(build_dir)
    check_dll_version(dll)
    sources = [p for d in ('src', 'include') for p in files_under(os.path.join(ROOT, d))
               if os.path.basename(p).lower() not in without]
    if newest(sources) > os.path.getmtime(dll):
        warnings.append('%s is older than the newest file in src/ or include/: rebuild with xmake'
                        % os.path.relpath(dll, ROOT))
    plugins = os.path.join(OUT, 'SKSE', 'Plugins')
    place(dll, os.path.join(plugins, DLL_NAME + '.dll'), origin)
    pdb = os.path.splitext(dll)[0] + '.pdb'
    if os.path.exists(pdb):  # lets crash loggers name functions
        place(pdb, os.path.join(plugins, DLL_NAME + '.pdb'), origin)
    # Overlays come first; a later folder's file at a path already placed is the one it replaces.
    for data in data_dirs:
        base = os.path.join(ROOT, data)
        for p in files_under(base, content_only=True):
            dest = os.path.join(OUT, os.path.relpath(p, base))
            if dest in origin and data != data_dirs[0]:
                continue
            place(p, dest, origin)
    return dll


def write_zip(mod_dir):
    """mods/<mod>.zip with the mod's content at the root. Archives inside the folder are left out."""
    name = os.path.basename(mod_dir)
    dest = os.path.join(ROOT, 'mods', name + '.zip')
    tmp = dest + '.tmp'
    count = 0
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in sorted(files_under(mod_dir), key=str.lower):
            if p.lower().endswith(ARCHIVES):
                continue
            z.write(p, os.path.relpath(p, mod_dir).replace(os.sep, '/'))
            count += 1
    os.replace(tmp, dest)
    return dest, count


def git_head():
    try:
        head = subprocess.run(['git', '-C', ROOT, 'rev-parse', '--short', 'HEAD'],
                              capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(['git', '-C', ROOT, 'status', '--porcelain', '--', 'mods', 'tools'],
                               capture_output=True, text=True).stdout
        generated = ['mods/%s/' % name for name, *_ in EDITIONS]
        dirty = [l for l in dirty.splitlines()
                 if not any(g in l for g in generated) and not l.rstrip('"').lower().endswith(ARCHIVES)]
        return head + (' (+ uncommitted changes in mods/ or tools/)' if dirty else '')
    except (OSError, subprocess.CalledProcessError):
        return 'unknown'


README = """# OStim Standalone Immersive Sex{edition}

OStim Expression Director (OSED) and its Body, Living Skin and Lip-Sync add-ons, rebuilt as
one SKSE plugin, plus an arousal-driven body response. This folder is generated by `tools/assemble_mod.py`;
`BUILD-OSIS.txt` records what went into it.

## What is in it

`SKSE/Plugins/OSIS.dll`. There is no plugin (.esp), no Papyrus script and no MCM.
Settings are in the SKSE Menu Framework (section "OSIS") and in
`SKSE/Plugins/OSIS.ini`; softbody morph and body-blush tables are in
`SKSE/Plugins/OSIS/morphs.json`, which also holds the per-race body-blush multipliers.
Settings you save in game are written to that INI, so
reinstalling this mod with "Replace" resets them to the defaults shipped here.

Changes from the originals that you'll notice:
- The Living Skin sweat layer is gone (a face overlay never lined up with the body).
- Arousal never drops to zero after an orgasm; it holds, then eases back to the reported level.
- Body (toe/finger curl) and Living Skin are on by default; the originals shipped them off.

## Before enabling

Disable these in MO2; this mod replaces all of them:
- the original **Ostim Expression Director (OSED)**, **OSED Body**, **OSED Living Skin**,
  and **OSED Enhanced Moan LipSync**;
- **OSED Reborn Core / Body / Living Skin / Lip-Sync**, if you installed them: those were
  Papyrus test builds of the same features, not add-ons for this one.

Start a new save for testing.

If one is left on by mistake, the DLL turns its own matching module off for that session instead
of fighting it, logs why, and shows one notification ("old mod(s) still active"); the Status page
lists them. Only the matching module stands down: with the old Core plugin active, for example,
the DLL still tracks scenes and runs body, skin, lip-sync and arousal, and only stops painting faces.

Every module can also be switched off on its own (General page, "Modules"), for when another mod
already does that job. Lip-Sync stands down by itself while Dynamic Dialogue Framework is
installed, since both drive the mouth; the Lip-Sync page can override that.

## Source and licence

This mod links CommonLibSSE-NG, which is licensed under the GNU General Public License v3, so
this mod is GPL-3.0 too.

OStim Standalone Immersive Sex (OSIS)
Copyright (C) 2026 jturnley

This program is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

The full licence text is in `LICENSE.txt` beside this file, and at
<https://www.gnu.org/licenses/gpl-3.0.html>.

Complete source code: <https://github.com/jturnley/OSIS>

## Requirements

SKSE64, Address Library for SKSE Plugins, OStim Standalone, SKSE Menu Framework, RaceMenu (skin
overlays), and Spell Perk Item Distributor (reads `OSED_Personality_DISTR.ini`).
"""


def main():
    global OUT
    for name, build_dir, data_dirs, edition, without in EDITIONS:
        OUT = os.path.join(ROOT, 'mods', name)
        warnings.clear()
        skipped.clear()
        assemble(build_dir, data_dirs, edition, without)
    return 0


def assemble(build_dir, data_dirs, edition, without):
    reset_output()
    origin = {}
    dll = add_dll_route(origin, build_dir, data_dirs, without)
    with open(os.path.join(OUT, 'README-OSIS.md'), 'w', encoding='utf-8') as f:
        f.write(README.replace('{edition}', edition))  # '' for the default download

    lines = [MARKER + ' on %s' % datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
             'Project commit: %s' % git_head(),
             'DLL: %s (built %s)' % (os.path.relpath(dll, ROOT),
                                     datetime.datetime.fromtimestamp(os.path.getmtime(dll)).strftime('%Y-%m-%d %H:%M')),
             '']
    lines += ['WARNING: ' + w for w in warnings]
    kept = foreign_files(origin)
    lines += ['Kept (not made by this script): ' + k for k in kept]
    lines += ['Skipped archive: ' + s for s in skipped]
    lines += ['', 'Files (size, source):']
    for dest in sorted(origin, key=lambda d: os.path.relpath(d, OUT).lower()):
        lines.append('  %-72s %9d  %s' % (os.path.relpath(dest, OUT), os.path.getsize(dest), origin[dest]))
    with open(os.path.join(OUT, 'BUILD-OSIS.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print('Wrote %s: %d files' % (os.path.relpath(OUT, ROOT), len(origin) + 2))
    for k in kept:
        print('kept (not ours): ' + k)
    for s in skipped:
        print('skipped archive: ' + s)
    dest, count = write_zip(OUT)
    print('zip: %s, %d files, %d bytes' % (os.path.relpath(dest, ROOT), count, os.path.getsize(dest)))
    for w in warnings:
        print('WARNING: ' + w)


if __name__ == '__main__':
    sys.exit(main())
