# SPDX-License-Identifier: GPL-3.0-or-later
# OStim Standalone Immersive Sex (OSIS) - Copyright (C) 2026 jturnley
# Free software under the GNU General Public License v3 or later; see LICENSE.

"""Assemble the MO2 mods of both editions from the xmake builds (`xmake build` makes both DLLs):
  mods/OStim Standalone Immersive Sex               the default release, compiled without the
                            non-consent features: build/lite/windows/x64/<mode>, plus dist/
  mods/OStim Standalone Immersive Sex (LoversLab)  the full plugin: build/windows/x64/<mode>, plus dist/
Each is OSIS.dll/.pdb plus the data folders (laid out like Data/). A folder listed first for an
edition would overlay dist/; none does now.

OSIS.ini and OSIS/morphs.json are not shipped: the plugin writes them on startup (and completes an
older INI), so installing an update over an old one cannot reset what the user chose.

The output folder is generated: each run deletes the files the previous run listed in
BUILD-OSIS.txt and writes a fresh set. Anything else in the folder (an archive you packed from it,
for example) is left alone. Archives are never copied in. This script never builds anything
itself; it warns when the DLL is older than its sources.

Finally it writes mods/<mod>.zip for each, installable in MO2 (the mod's files at the zip root,
so MO2 names the mod after the zip and finds its data directly).

Usage: python tools/assemble_mod.py [--patch]

With --patch it also writes mods/<mod> - <label> patch.zip for each: just the DLL and the README, to install over the
release before it (a hotfix). Without the PDB, so it is small; a crash log from it is read against the PDB kept in mods/<mod>/.
"""
import datetime
import os
import re
import shutil
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# (mod folder, build folder, data folders: overlays first, dist last, README title suffix,
#  source files the edition's DLL is built without)
EDITIONS = [
    ('OStim Standalone Immersive Sex', os.path.join('build', 'lite', 'windows', 'x64'), ['dist'], '',
     {'voice.cpp', 'voice.h', 'scenelock.cpp', 'scenelock.h', 'spellcast.cpp', 'spellcast.h'}),
    ('OStim Standalone Immersive Sex (LoversLab)', os.path.join('build', 'windows', 'x64'), ['dist'], ' (LoversLab edition)', set()),
]
OUT = os.path.join(ROOT, 'mods', EDITIONS[0][0])  # the edition being assembled
MARKER = 'Generated by tools/assemble_mod.py'
DLL_NAME = 'OSIS'
BUILD_MODES = ['releasedbg', 'release', 'debug']  # preference order
ARCHIVES = ('.7z', '.zip', '.rar')  # packed copies of a mod folder, not mod content
MANIFEST_LINE = re.compile(r'^  (.+?) +\d+  .+$')

warnings = []
skipped = []


def newest(paths):
    return max((os.path.getmtime(p) for p in paths), default=0.0)


def files_under(d, content_only=False):
    for base, _dirs, names in os.walk(d):
        for n in names:
            p = os.path.join(base, n)
            if content_only and n.lower().endswith(ARCHIVES):
                skipped.append(os.path.relpath(p, ROOT))
                continue
            yield p


def place(src, dest, origin):
    """Copy src to dest; an existing identical file is fine, a different one is an error."""
    if os.path.exists(dest):
        with open(src, 'rb') as a, open(dest, 'rb') as b:
            same = a.read() == b.read()
        if not same:
            raise SystemExit('conflict: %s differs from the copy already placed at %s (from %s)'
                             % (src, os.path.relpath(dest, OUT), origin.get(dest)))
        return
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    shutil.copy2(src, dest)
    origin[dest] = os.path.relpath(src, ROOT)


def reset_output():
    """Delete what the previous run made (the files BUILD-OSIS.txt lists, plus BUILD-OSIS.txt and README-OSIS.md),
    then prune empty folders. Other files stay. The folder itself stays too: Windows can't remove
    a folder that is open in Explorer or is some process's working directory."""
    os.makedirs(OUT, exist_ok=True)
    build = os.path.join(OUT, 'BUILD-OSIS.txt')
    if not os.path.exists(build):
        if os.listdir(OUT):
            raise SystemExit('%s has files but no BUILD-OSIS.txt from this script; not touching it.' % OUT)
        return
    with open(build, encoding='utf-8') as f:
        lines = f.read().splitlines()
    if not lines or not lines[0].startswith(MARKER):
        raise SystemExit('%s/BUILD-OSIS.txt was not written by this script; not touching the folder.' % OUT)
    ours = ['BUILD-OSIS.txt', 'README-OSIS.md']
    in_files = False
    for line in lines:
        if line.startswith('Files (size, source):'):
            in_files = True
        elif in_files and MANIFEST_LINE.match(line):
            ours.append(MANIFEST_LINE.match(line).group(1))
    for rel in ours:
        p = os.path.join(OUT, rel)
        if os.path.isfile(p):
            os.remove(p)
    for base, dirs, files in os.walk(OUT, topdown=False):
        if base != OUT and not os.listdir(base):
            os.rmdir(base)


def foreign_files(origin):
    """Files in the output folder that this run did not write."""
    made = {os.path.normcase(p) for p in origin} | {os.path.normcase(os.path.join(OUT, n)) for n in ('BUILD-OSIS.txt', 'README-OSIS.md')}
    return sorted(os.path.relpath(p, OUT) for p in files_under(OUT) if os.path.normcase(p) not in made)


def find_dll(build_dir):
    for mode in BUILD_MODES:
        dll = os.path.join(ROOT, build_dir, mode, DLL_NAME + '.dll')
        if os.path.exists(dll):
            if mode != BUILD_MODES[0]:
                warnings.append('using the %s DLL build, not %s' % (mode, BUILD_MODES[0]))
            return dll
    raise SystemExit('no %s.dll under %s/{%s}; build it with xmake first'
                     % (DLL_NAME, build_dir.replace(os.sep, '/'), ','.join(BUILD_MODES)))


def project_version():
    """The version xmake.lua declares, as "1.2.3"."""
    with open(os.path.join(ROOT, 'xmake.lua'), encoding='utf-8') as f:
        m = re.search(r'set_version\("([0-9]+\.[0-9]+\.[0-9]+)"\)', f.read())
    return m.group(1) if m else None


def release_label():
    """The label src/Release.h declares ("beta 1"), or "" for a final release."""
    with open(os.path.join(ROOT, 'src', 'Release.h'), encoding='utf-8') as f:
        m = re.search(r'kLabel\s*=\s*"([^"]*)"', f.read())
    return m.group(1) if m else ''


def version_text():
    """"2.0.0 beta 1": the version xmake.lua declares, then the label."""
    label = release_label()
    return project_version() + (' ' + label if label else '')


def check_dll_version(dll):
    """The version resource is UTF-16 in the PE, so the declared version shows up as plain
    bytes. Missing means xmake reused a stale generated plugin-info file: the DLL would load,
    report the previous version, and make every later log and crash report misleading."""
    want = project_version()
    if not want:
        warnings.append('could not read set_version from xmake.lua; DLL version not checked')
        return
    with open(dll, 'rb') as f:
        blob = f.read()
    if ('%s.0' % want).encode('utf-16-le') in blob:
        return
    raise SystemExit(
        '%s does not carry version %s: xmake kept a stale plugin-info file.\n'
        '  Delete build/.gens/*/windows/x64/*/commonlibsse-ng-plugin.cpp and build again.'
        % (os.path.relpath(dll, ROOT), want))


def add_dll_route(origin, build_dir, data_dirs, without):
    dll = find_dll(build_dir)
    check_dll_version(dll)
    sources = [p for d in ('src', 'include') for p in files_under(os.path.join(ROOT, d))
               if os.path.basename(p).lower() not in without]
    if newest(sources) > os.path.getmtime(dll):
        warnings.append('%s is older than the newest file in src/ or include/: rebuild with xmake'
                        % os.path.relpath(dll, ROOT))
    plugins = os.path.join(OUT, 'SKSE', 'Plugins')
    place(dll, os.path.join(plugins, DLL_NAME + '.dll'), origin)
    pdb = os.path.splitext(dll)[0] + '.pdb'
    if os.path.exists(pdb):  # lets crash loggers name functions
        place(pdb, os.path.join(plugins, DLL_NAME + '.pdb'), origin)
    # Overlays come first; a later folder's file at a path already placed is the one it replaces.
    for data in data_dirs:
        base = os.path.join(ROOT, data)
        for p in files_under(base, content_only=True):
            dest = os.path.join(OUT, os.path.relpath(p, base))
            if dest in origin and data != data_dirs[0]:
                continue
            place(p, dest, origin)
    return dll


def write_zip(mod_dir):
    """mods/<mod>.zip with the mod's content at the root. Archives inside the folder are left out."""
    name = os.path.basename(mod_dir)
    dest = os.path.join(ROOT, 'mods', name + '.zip')
    tmp = dest + '.tmp'
    count = 0
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in sorted(files_under(mod_dir), key=str.lower):
            if p.lower().endswith(ARCHIVES):
                continue
            z.write(p, os.path.relpath(p, mod_dir).replace(os.sep, '/'))
            count += 1
    os.replace(tmp, dest)
    return dest, count


PATCH_FILES = ("SKSE/Plugins/OSIS.dll", "README-OSIS.md")  # not the PDB: it is 35 MB, nearly the whole of the full archive


def write_patch(mod_dir):
    """mods/<mod> - <label> patch.zip: the files a hotfix replaces, at the root like the full archive."""
    name = os.path.basename(mod_dir)
    dest = os.path.join(ROOT, 'mods', '%s - %s patch.zip' % (name, release_label() or project_version()))
    tmp = dest + '.tmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for rel in PATCH_FILES:
            z.write(os.path.join(mod_dir, *rel.split('/')), rel)
    os.replace(tmp, dest)
    return dest


def git_head():
    try:
        head = subprocess.run(['git', '-C', ROOT, 'rev-parse', '--short', 'HEAD'],
                              capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(['git', '-C', ROOT, 'status', '--porcelain', '--', 'mods', 'tools'],
                               capture_output=True, text=True).stdout
        generated = ['mods/%s/' % name for name, *_ in EDITIONS]
        dirty = [l for l in dirty.splitlines()
                 if not any(g in l for g in generated) and not l.rstrip('"').lower().endswith(ARCHIVES)]
        return head + (' (+ uncommitted changes in mods/ or tools/)' if dirty else '')
    except (OSError, subprocess.CalledProcessError):
        return 'unknown'


README = """# OStim Standalone Immersive Sex{edition}

**Version {version}**
{beta}
OStim Expression Director (OSED) and its Body, Living Skin and Lip-Sync add-ons, rebuilt as
one SKSE plugin, plus an arousal-driven body response. This folder is generated by `tools/assemble_mod.py`;
`BUILD-OSIS.txt` records what went into it.

## What is in it

`SKSE/Plugins/OSIS.dll`. There is no plugin (.esp), no Papyrus script and no MCM.
Settings are in the SKSE Menu Framework (section "OSIS"). They are kept in
`SKSE/Plugins/OSIS.ini`; the softbody morph and body-blush tables, with the per-race body-blush
multipliers, are in `SKSE/Plugins/OSIS/morphs.json`. The mod does not ship either file: the plugin
creates them the first time the game runs with it, and adds to the INI any setting a newer version
introduces. Updating the mod therefore keeps what you chose; delete a file to go back to its defaults.

Changes from the originals that you'll notice:
- The Living Skin sweat layer is gone (a face overlay never lined up with the body).
- Arousal never drops to zero after an orgasm; it holds, then eases back to the reported level.
- Body (toe/finger curl) and Living Skin are on by default; the originals shipped them off.

## How the face works (Director, the default)

The Director reads OStim's own facial expression files (every installed expression pack applies), picks from
the pool OStim would use for what each actor is doing, and blends from one pick to the next, so there are no
snaps. OStim's own face writer is switched off for the actors OSIS paints and given back when the scene ends.
Picks are weighted by the actor's personality. The build-up mixes OStim's pools with 110 faces of the Director's own
(five stages of 22), and each orgasm is played as one of fifteen timed climax faces, shorter and tenser the closer it comes to the
last. An actor OStim says is asleep has the eyes shut. Assist and Enhanced (OSIS layered over OStim's own faces) are still on the Face page.

## Bodies and arousal

The arousal morphs and body blush are set up for CBBE/3BA (GT Softbody sliders, Body Blushing textures). UBE bodies are found by their
race (`00UBE_*`) and have rows of their own, with the UBE sliders and UBE blush regions; every row on the Arousal page has a body type.
The UBE blush textures are not shipped: convert Body Blushing's to the UBE UV and put them in
`Data/Textures/actors/Character/Overlays/CheeseBlushOverlays_UBE/`. Toe and finger curl work on any body that uses the stock skeleton.
The morphs and blush follow the arousal during OStim scenes and are put back as the scene ends; "Arousal features slowly fade after scene"
(Arousal page, off by default) eases them back over a few seconds instead, which can raise GPU load. "Also outside OStim scenes" (off by default)
keeps them following an arousal mod's number all the time, which costs resources.

## Personalities

Each actor gets a personality (stoic, vocal, shy, dominant, timid, wild, crazed{submissive} or none) the first time a
scene needs it, from a SPID keyword, its voice type, its AI values or a seeded roll (mostly balanced, few dominant; the shipped SPID file hands out none). It is then kept in
your save, so it is the same in every scene and after every load. Set one yourself on the Personality page (the
player's, or the NPC under the crosshair); "Work every personality out again" forgets the automatic ones.

- **Stoic**: tolerates sex but isn't into it, and is waiting for the partner to be done. Slow to build, muted at the plateau and the
  climax, nothing negative in it. Only physiological body reactions, minimal; no blush, face or body, until the last seconds before the
  orgasm and during it, then it fades quickly.
- **Shy**: uncomfortable with the idea of sex, though they enjoy it. Hesitation and guilt, overridden as they plateau and climax.
- **Timid**: enjoys it a lot, but the closeness is too much. Eyes shut much of the time, an occasional peek at the partner.
- **Vocal**: likes it a lot but has no control over themselves. Surprise, and loud voices.
- **Wild**: enjoys every moment, the intimacy and the pleasure alike. Only positive reactions, and they try to maximise them.
- **Dominant**: their own pleasure comes first, and the partner is a toy. Their partner's climax is held (OStim's climax stall)
  until the dominant's own, and the two climax together.
- **Crazed**: obsessed with the partner. Long, creepy eye contact; drives the partner up to climax as fast as it can and climaxes
  with them, with a creepy look, every time they do.{submissive_note}

Dominant and crazed control climaxes in consensual scenes only; "Dominant and crazed people control a partner's climax" on the
Personality page turns it off.

## PPA - Procedural Penis Animations (optional)

While PPA is playing its mouth preset on whoever is giving a blowjob, OSIS leaves their mouth, and where they
look, to it, and takes the mouth back if PPA turns out not to be driving it (Face > Mouth). If PPA's preset also
zeroes the eyes and brows, as the one that ships with [Predator] SMP Head does, the Mouth page says so and
offers "Keep OSIS's eyes and brows", which writes `00_OSIS_PPA_Face.toml` into PPA's `ppa-override-configs`.
"Restore PPA's own setting" deletes it again. No other mod's file is changed. PPA reads its configs at startup
or on its reload key (F5 by default).
{known}
## Before enabling

Disable these in MO2; this mod replaces all of them:
- the original **Ostim Expression Director (OSED)**, **OSED Body**, **OSED Living Skin**,
  and **OSED Enhanced Moan LipSync**;
- **OSED Reborn Core / Body / Living Skin / Lip-Sync**, if you installed them: those were
  Papyrus test builds of the same features, not add-ons for this one.

Start a new save for testing.

If one is left on by mistake, the DLL turns its own matching module off for that session instead
of fighting it, logs why, and shows one notification ("old mod(s) still active"); the Status page
lists them. Only the matching module stands down: with the old Core plugin active, for example,
the DLL still tracks scenes and runs body, skin, lip-sync and arousal, and only stops painting faces.

Every module can also be switched off on its own (General page, "Modules"), for when another mod
already does that job. Lip-Sync stands down by itself while Dynamic Dialogue Framework is
installed, since both drive the mouth; the Lip-Sync page can override that.

## Source and licence

This mod links CommonLibSSE-NG, which is licensed under the GNU General Public License v3, so
this mod is GPL-3.0 too.

OStim Standalone Immersive Sex (OSIS)
Copyright (C) 2026 jturnley

This program is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

The full licence text is in `LICENSE.txt` beside this file, and at
<https://www.gnu.org/licenses/gpl-3.0.html>.

Complete source code: <https://github.com/jturnley/OSIS>

## Requirements

SKSE64, Address Library for SKSE Plugins, OStim Standalone, SKSE Menu Framework, RaceMenu (skin
overlays), and Spell Perk Item Distributor (reads `OSIS_Personality_DISTR.ini`). PPA is optional.
"""


def main():
    global OUT
    for name, build_dir, data_dirs, edition, without in EDITIONS:
        OUT = os.path.join(ROOT, 'mods', name)
        warnings.clear()
        skipped.clear()
        assemble(build_dir, data_dirs, edition, without)
        if '--patch' in sys.argv[1:]:
            dest = write_patch(OUT)
            print('patch: %s, %d bytes' % (os.path.relpath(dest, ROOT), os.path.getsize(dest)))
    return 0


def assemble(build_dir, data_dirs, edition, without):
    reset_output()
    origin = {}
    dll = add_dll_route(origin, build_dir, data_dirs, without)
    with open(os.path.join(OUT, 'README-OSIS.md'), 'w', encoding='utf-8') as f:
        beta = ''
        known = ''
        if release_label():
            beta = ("\n> **This is a beta.** It is complete enough to use but has had limited testing. Back up your save, and send\n"
                    "> `Documents/My Games/Skyrim Special Edition/SKSE/OSIS.log` with any report. For a face problem, press\n"
                    "> \"Probe faces\" on the Face page first and play for a minute.\n")
            known = ("\n## Known issues in this beta\n\n"
                     "- A one-frame blink of eyes, brows and mood can show when a scene moves to a new animation node.\n"
                     "- PPA sometimes stops moving a penis for a few seconds and logs \"isn't managed by havok\" for the actor. Seen in testing; the cause is not known.\n"
                     "- Lip-sync reads uncompressed WAV moans only: voice packs in .fuz or xWMA, and packs of spoken lines, are not lip-synced.\n"
                     "- UBE: the blush textures are not shipped (convert Body Blushing's to the UBE UV) and the UBE slider values are a first estimate.\n"
                     "- The personalities, the own build-up faces and the shaped body response are new and have had little play-testing.\n")
        submissive = ''
        if edition:  # the personality is in the full edition only
            submissive = ("\n- **Submissive** (this edition only): turned on by rough scenes, and accepts any kind of scene, forced or not,"
                          " from someone with a relationship rank of 3 or 4 to everyone in it; it then plays as consensual.")
        f.write(README.replace('{edition}', edition).replace('{version}', version_text())
                .replace('{submissive_note}', submissive).replace('{submissive}', ', submissive' if edition else '')
                .replace('{beta}', beta).replace('{known}', known))  # edition is '' for the default download

    lines = [MARKER + ' on %s' % datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
             'Project commit: %s' % git_head(),
             'DLL: %s (built %s)' % (os.path.relpath(dll, ROOT),
                                     datetime.datetime.fromtimestamp(os.path.getmtime(dll)).strftime('%Y-%m-%d %H:%M')),
             '']
    lines += ['WARNING: ' + w for w in warnings]
    kept = foreign_files(origin)
    lines += ['Kept (not made by this script): ' + k for k in kept]
    lines += ['Skipped archive: ' + s for s in skipped]
    lines += ['', 'Files (size, source):']
    for dest in sorted(origin, key=lambda d: os.path.relpath(d, OUT).lower()):
        lines.append('  %-72s %9d  %s' % (os.path.relpath(dest, OUT), os.path.getsize(dest), origin[dest]))
    with open(os.path.join(OUT, 'BUILD-OSIS.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print('Wrote %s: %d files' % (os.path.relpath(OUT, ROOT), len(origin) + 2))
    for k in kept:
        print('kept (not ours): ' + k)
    for s in skipped:
        print('skipped archive: ' + s)
    dest, count = write_zip(OUT)
    print('zip: %s, %d files, %d bytes' % (os.path.relpath(dest, ROOT), count, os.path.getsize(dest)))
    for w in warnings:
        print('WARNING: ' + w)


if __name__ == '__main__':
    sys.exit(main())
