"""Generate a compile-only .psc header from a compiled Skyrim .pex.

Used for SkyUI's SKI_ConfigBase / SKI_QuestBase, which ship as .pex only inside SkyUI_SE.bsa.
The PapyrusCompiler needs source for every import, but only the declarations matter to a
caller: bodies are left empty and the output is never compiled into anything we ship.

.pex files don't record parameter defaults (the compiler applies them at the call site from
source), so DEFAULTS restores the ones the SkyUI SDK declares, matched by parameter name.

Usage: python tools/pex_stub.py <in.pex> <out.psc>
"""
import struct
import sys

# SkyUI SDK default values, keyed by parameter name. Only applied to trailing parameters.
DEFAULTS = {
    'a_flags': '0',
    'a_noupdate': 'False',
    'a_formatstring': '"{0}"',
    'a_withcancel': 'True',
    'a_acceptlabel': '"$Accept"',
    'a_cancellabel': '"$Cancel"',
    'a_x': '0.0',
    'a_y': '0.0',
    'a_statename': '""',
}
NO_DEFAULTS = {'setoptionflags', 'setoptionflagsst'}  # SDK leaves a_flags required here
COMPILER_GENERATED = {'getstate', 'gotostate'}  # emitted into every script; redeclaring them fails

# Opcode -> fixed argument count. Opcodes 23-25 (call*) are followed by a vararg list.
OP_ARGS = [0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 2, 2,
           3, 2, 3, 1, 3, 3, 3, 2, 2, 3, 3, 4, 4]
VARARG_OPS = (23, 24, 25)


class Reader:
    def __init__(self, data):
        self.d, self.i = data, 0

    def take(self, fmt):
        v = struct.unpack_from('>' + fmt, self.d, self.i)
        self.i += struct.calcsize('>' + fmt)
        return v[0] if len(v) == 1 else v

    def wstr(self):
        n = self.take('H')
        s = self.d[self.i:self.i + n].decode('cp1252')
        self.i += n
        return s


def parse(data):
    r = Reader(data)
    assert r.take('I') == 0xFA57C0DE, 'not a Skyrim .pex'
    r.take('BBHQ')
    for _ in range(3):
        r.wstr()
    strings = [r.wstr() for _ in range(r.take('H'))]
    S = lambda: strings[r.take('H')]

    def value():
        t = r.take('B')
        if t in (1, 2):
            return strings[r.take('H')]
        if t == 3:
            return r.take('i')
        if t == 4:
            return r.take('f')
        if t == 5:
            return r.take('B')
        return None

    def function():
        ret, _doc, uflags, flags = S(), S(), r.take('I'), r.take('B')
        params = [(S(), S()) for _ in range(r.take('H'))]
        for _ in range(r.take('H')):
            S(); S()
        for _ in range(r.take('H')):
            op = r.take('B')
            for _ in range(OP_ARGS[op]):
                value()
            if op in VARARG_OPS:
                for _ in range(value()):
                    value()
        return {'ret': ret, 'uflags': uflags, 'global': bool(flags & 1), 'native': bool(flags & 2),
                'params': params}

    if r.take('B'):  # debug info
        r.take('Q')
        for _ in range(r.take('H')):
            r.take('HHHB')
            for _ in range(r.take('H')):  # line numbers
                r.take('H')
    for _ in range(r.take('H')):  # user flag names
        S(); r.take('B')

    objects = []
    for _ in range(r.take('H')):
        name = S()
        r.take('I')
        obj = {'name': name, 'parent': S(), 'doc': S(), 'uflags': r.take('I'), 'auto_state': S(),
               'props': [], 'funcs': []}
        for _ in range(r.take('H')):  # variables (private to the script)
            S(); S(); r.take('I'); value()
        for _ in range(r.take('H')):
            p = {'name': S(), 'type': S(), 'doc': S(), 'uflags': r.take('I')}
            flags = r.take('B')
            if flags & 4:
                S()
            else:
                if flags & 1:
                    function()
                if flags & 2:
                    function()
            obj['props'].append(p)
        for _ in range(r.take('H')):  # states
            state = S()
            for _ in range(r.take('H')):
                fname = S()
                f = function()
                if state == '':
                    f['name'] = fname
                    obj['funcs'].append(f)
        objects.append(obj)
    return objects


def ptype(t):
    return 'Int' if t.lower() == 'int' else t


def render(obj):
    out = ['; Compile-only header generated by tools/pex_stub.py from %s.pex. Not for shipping.' % obj['name']]
    head = 'Scriptname %s' % obj['name']
    if obj['parent']:
        head += ' extends %s' % obj['parent']
    if obj['uflags'] & 1:
        head += ' Hidden'
    out += [head, '']
    for p in obj['props']:
        out.append('%s Property %s Auto%s' % (p['type'], p['name'], ' Hidden' if p['uflags'] & 1 else ''))
    out.append('')
    for f in obj['funcs']:
        if f['name'].lower() in COMPILER_GENERATED:
            continue
        params = list(f['params'])
        rendered = []
        trailing = True
        keep_flags = f['name'].lower() in NO_DEFAULTS
        for pname, ptyp in reversed(params):
            d = DEFAULTS.get(pname.lower()) if trailing else None
            if keep_flags and pname.lower() == 'a_flags':
                d = None
            trailing = trailing and d is not None
            rendered.append('%s %s%s' % (ptype(ptyp), pname, (' = ' + d) if d else ''))
        args = ', '.join(reversed(rendered))
        ret = f['ret']
        is_event = ret.lower() == 'none' and f['name'].lower().startswith('on') and not f['global']
        mods = (' Global' if f['global'] else '') + (' Native' if f['native'] else '')
        if is_event:
            out.append('Event %s(%s)%s' % (f['name'], args, mods))
            if not f['native']:
                out.append('EndEvent')
        else:
            prefix = '' if ret.lower() == 'none' else ret + ' '
            out.append('%sFunction %s(%s)%s' % (prefix, f['name'], args, mods))
            if not f['native']:
                out.append('EndFunction')
        out.append('')
    return '\n'.join(out)


def main():
    objs = parse(open(sys.argv[1], 'rb').read())
    open(sys.argv[2], 'w', encoding='utf-8', newline='\r\n').write(render(objs[0]))


if __name__ == '__main__':
    main()
